name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    uses: appleboy/ssh-action@master
    with:
      host: ${{secrets.SSH_HOST}}
      key: ${{secrets.SSH_KEY}}
      username: ${{secrets.SSH_USER}}

      script: |
        cd portfolio
        git pull
        npm install --legacy-peer-deps
        gatsby build
