name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          # key: ${{secrets.SSH_KEY}}
          password: ${{secrets.SSH_PASS}}

          script: |
            cd portfolio
            git pull
            npm install --legacy-peer-deps
            gatsby build 
